USE ham_exam;
INSERT INTO exam_subelements(subelement_name, description)
VALUES ("T1", "COMMISSION'S RULES"),
("T2", "OPERATING PROCEDURES"),
("T3", "RADIO WAVE PROPAGATION"),
("T4", "AMATEUR RADIO PRACTICES"),
("T5", "ELECTRICAL PRINCIPLES"),
("T6", "ELECTRONIC AND ELECTRICAL COMPONENTS"),
("T7", "PRACTICAL CIRCUITS"),
("T8", "SIGNALS AND EMISSIONS"),
("T9", "ANTENNAS AND FEED LINES"),
("T0", "SAFETY");